### ISSUE TITLE
Multiple Bluetooth Headsets

### ISSUE THREAD

**Issue by cyodrew** [twilio/audioswitch#15]
**Is your feature request related to a problem? Please describe.**
Android phones often allow multiple Bluetooth headsets to be bonded at once. The library only seems to populate and connect to the last one in the found bonded devices.

**Describe the solution you'd like**
The dialog presented to the user should show all Bluetooth devices rather than one and allow the ability to switch between them.

**Describe alternatives you've considered**
Currently, the only way to accomplish this is to manually disconnect one of the devices from the phone settings or turning off the Bluetooth device. The sample app `twilio-quickstart-android` usually needs to be restarted for the change to be reflected.

**Additional context**
I was able to load in the list of bonded Bluetooth devices after modifying the source code myself by switching the variable `bluetoothAudioDevice: AudioDevice` to `ArrayList<AudioDevice>` and other code relevant to making the variable into a mutable list. However, the challenge seems to be the API that Android provides for switching Bluetooth devices. The method `startBluetoothSco()` does not provide a way to specify a device.

**Comment by Alton09** [comment]
Hi @cyodrew! Thank you for reaching out regarding this enhancement. This is definitely a realistic scenario that the library should handle. I will go ahead and add a spike story to our backlog to investigate this more, as you have pointed out, there may be a limitation due to the `startBluetoothSco` method.

**Comment by babramovitch** [comment]
Hi,

This feature would be great to have.  We've implemented it in our app outside of this library by using some bluetooth admin commands (requires permission) on the BluetoothHeadset object.  

If we could get this in the Twilio SDK we would prefer to use it would allow the community as whole to improve it and fix all the oddities the OS throws at us.

Feel free to reach out to discuss as you look into implementing this

@SystemApi
@RequiresPermission(android.Manifest.permission.BLUETOOTH_ADMIN)
public boolean connect(BluetoothDevice device) 

@SystemApi
@RequiresPermission(android.Manifest.permission.BLUETOOTH_ADMIN)
public boolean disconnect(BluetoothDevice device) 

 @SystemApi
 @RequiresPermission(android.Manifest.permission.BLUETOOTH_ADMIN)
 public boolean setPriority(BluetoothDevice device, int priority) 

We used setPriority to ensure that when Bluetooth SCO started, it would choose the device the user manually chose should the other headset reconnect during the call.  Priorities were then set back when the call ended.

**Comment by Alton09** [comment]
Thanks for the input @babramovitch ! I'm glad to see you were able to get this working in the meantime. We are planning to look into support for this soon in one of our upcoming sprints.

**Comment by Alton09** [comment]
@cyodrew @babramovitch Here's an update regarding our research into supporting multiple bluetooth devices. It appears that the only way to be able to change the active (meaning audio is routed to the device) bluetooth device is through calling the `setActiveDevice()` method from the `BluetoothHeadset` class. Unfortunately this is a system API method, similar to the other system method calls that @babramovitch mentioned above. Although this solution works with reflection, we are hesitant to begin implementation on this right away as it has been Greylisted as a [non-SDK interface](https://developer.android.com/distribute/best-practices/develop/restrictions-non-sdk-interfaces) and could be potentially Blacklisted in a future Android release. In response to that, we created a new API request on Google Issue Tracker so that Google can consider creating a public SDK interface to handle this functionality. [Here](https://issuetracker.google.com/issues/160762357) is the link for that issue, but for some reason the component that it is under limits the visibility to the requester and Google's team. In the meantime, we are going to make sure that this library accurately represents a single active bluetooth headset, even if multiple headsets are connected. I'll provide more updates regarding this enhancement as we learn more. Thanks!

**Comment by babramovitch** [comment]
@Alton09 The only way to change device when multiple are connected is setActiveDevice, but the solution I worked out didn't change devices specifically, it disconnected one and connected the other.  

Both of those API's are listed as system-api and whitelisted, so I would not expect them to become blacklisted if that path was used.

**Comment by Alton09** [comment]
@babramovitch @cyodrew The library now provides support for multiple bluetooth headsets! Check out the latest version, [0.2.0](https://github.com/twilio/audioswitch/releases/tag/0.2.0). It doesn't allow users to select from a list of devices in the library, but it does accurately show the active bluetooth headset, even when changing the active headset in the bluetooth settings system app.

**Comment by aaalaniz** [comment]
Hey @babramovitch @cyodrew 

In our research, we found that we would not be able to offer in-app Bluetooth Headset selection without using reflection of the Android Bluetooth APIs. As a result, we decided to support multiple Bluetooth devices by allowing users to switch Bluetooth devices from the Bluetooth settings. This behavior is consistent with what is done in Google Meet with multiple bluetooth devices and requires no non-public APIs. Please see the [Bluetooth Support](https://github.com/twilio/audioswitch#bluetooth-support) section of the README for more details.

We will close this issue as officially supported in part to the merging of #40 released in [0.2.0](https://github.com/twilio/audioswitch/releases/tag/0.2.0).

If we find that we can support selecting a specific bluetooth device with public APIs, we will reprioritize.

Thanks!
